// lib/services/seed/prompts/photo_enhancement_prompts.dart

class PhotoEnhancementPrompts {
  static List<Map<String, String>> getPrompts(String subcategory) {
    switch (subcategory) {

      case 'Upscale HD':
        return [
          {'title': '4K Portrait Upscale', 'platform': 'Topaz Gigapixel', 'description': 'Upscale portrait photo to 4K', 'text': 'Upscale this portrait photo to 4K ultra HD resolution, enhance facial detail and skin texture, recover hair strand detail, sharpen eyes without artifacts, preserve natural skin tones, professional quality upscaling'},
          {'title': 'Old Photo HD Restore', 'platform': 'Remini', 'description': 'Upscale old low quality photo', 'text': 'Enhance and upscale this old low resolution photo to HD quality, fill in missing detail with AI, sharpen blurry edges, restore facial features, maintain original composition, realistic enhancement'},
          {'title': 'Wedding Photo 8K', 'platform': 'Topaz Gigapixel', 'description': 'Upscale wedding photo to 8K', 'text': 'Upscale this wedding photo to 8K print-ready resolution, enhance fabric and embroidery texture of lehenga and sherwani, recover jewelry detail, sharpen faces, ready for large canvas print'},
          {'title': 'Landscape Photo Print', 'platform': 'Adobe Super Res', 'description': 'Landscape photo for large print', 'text': 'Upscale this landscape photo to billboard print resolution, enhance cloud and mountain texture, recover fine tree detail, sharpen water reflections, artifact-free upscaling for large format print'},
          {'title': 'Product Photo Enhance', 'platform': 'Topaz Gigapixel', 'description': 'Product photo to HD for e-commerce', 'text': 'Upscale this product photo to high resolution e-commerce quality, enhance material texture and surface detail, recover fine print on packaging, sharp edges on product, Amazon listing quality'},
          {'title': 'Group Photo Clarity', 'platform': 'Remini', 'description': 'Group photo faces sharpened', 'text': 'Upscale this group photo and enhance clarity of all faces simultaneously, sharpen background without noise, recover clothing texture detail, enhance to printable quality for framing'},
          {'title': 'Vintage Film Upscale', 'platform': 'Adobe Super Res', 'description': 'Film scan upscaled to HD', 'text': 'Upscale this 35mm film scan to digital HD quality, preserve film grain character while enhancing detail, sharpen subject while maintaining vintage film aesthetic, analog feel with digital clarity'},
          {'title': 'WhatsApp Photo Fix', 'platform': 'Topaz Gigapixel', 'description': 'Low quality WhatsApp photo enhanced', 'text': 'Enhance this heavily compressed WhatsApp forwarded photo, remove JPEG compression artifacts, recover lost detail, upscale to sharp viewable quality, fix blurry and pixelated look'},
          {'title': 'Screenshot Enhance', 'platform': 'Remini', 'description': 'Screenshot upscaled to clear image', 'text': 'Upscale and enhance this screenshot image to full resolution quality, remove pixelation and aliasing, sharpen text and edges, enhance UI elements to crisp HD clarity'},
          {'title': 'Baby Photo Restore 4K', 'platform': 'Adobe Super Res', 'description': 'Old baby photo to HD', 'text': 'Upscale this precious old baby photo to 4K quality, recover soft facial features of baby, enhance skin texture naturally, sharpen eyes gently, ready for beautiful frame and gift print'},
        ];

      case 'Old Photo Restore':
        return [
          {'title': 'Grandfather Portrait Fix', 'platform': 'MyHeritage', 'description': 'Restore old grandfather photo', 'text': 'Restore this damaged old photograph of grandfather, repair torn edges and fold creases, remove scratches and stains, enhance facial detail, convert to clear sepia or natural tone, family heirloom quality'},
          {'title': 'Black White Colorize', 'platform': 'Palette.fm', 'description': 'Add color to old black white photo', 'text': 'Add realistic natural color to this old black and white family photograph, accurate skin tones, natural clothing colors of the era, realistic background, colorization that looks authentic not artificial'},
          {'title': 'Wedding 1970s Restore', 'platform': 'MyHeritage', 'description': 'Restore faded 1970s wedding photo', 'text': 'Restore and enhance this faded 1970s wedding photograph, recover color from yellowed photo, repair water damage stains, enhance bride and groom faces, preserve original composition and era feel'},
          {'title': 'War Era Photo Repair', 'platform': 'Adobe Photoshop AI', 'description': 'Restore historical era photo', 'text': 'Carefully restore this historical era photograph, remove extensive damage, fill missing parts intelligently, enhance military uniform or period clothing detail, preserve historical authenticity'},
          {'title': 'School Photo Decade Old', 'platform': 'Remini', 'description': 'Old school annual photo enhanced', 'text': 'Restore and enhance this old school annual photograph, sharpen multiple faces in group, repair faded colors, remove age spots and foxing, frame-ready quality enhancement'},
          {'title': 'Torn Photo Reconstruction', 'platform': 'Adobe Photoshop AI', 'description': 'Reconstruct torn photo pieces', 'text': 'Reconstruct and restore this torn photograph, intelligently fill missing torn areas, seamlessly repair tear lines, restore missing facial features using AI, make the photo whole again'},
          {'title': 'Fire Damaged Photo', 'platform': 'MyHeritage', 'description': 'Restore fire or water damaged photo', 'text': 'Restore this fire and smoke damaged photograph, remove burn marks and darkened areas, recover original image from damaged areas, enhance surviving detail, family memory restoration'},
          {'title': 'Passport Retro Restore', 'platform': 'Palette.fm', 'description': 'Restore old passport or ID photo', 'text': 'Restore this old passport or identity photograph, sharpen and clarify face detail, remove foxing and age damage, enhance to clear modern quality, historical identity document photo restoration'},
          {'title': 'Festival Celebration Old', 'platform': 'Adobe Photoshop AI', 'description': 'Restore old festival photo', 'text': 'Restore this old Diwali or Holi family celebration photograph, recover vibrant festival colors that have faded, repair physical damage, enhance all faces in the celebration group'},
          {'title': 'Temple Pilgrimage Photo', 'platform': 'Remini', 'description': 'Restore old pilgrimage photo', 'text': 'Restore this old temple pilgrimage family photograph, repair yellowing and fading, enhance architectural temple details in background, sharpen family faces, frame ready restoration'},
        ];

      case 'Background Remove':
        return [
          {'title': 'Product White Background', 'platform': 'Remove.bg', 'description': 'Remove background for e-commerce', 'text': 'Remove background from this product photo and replace with pure clean white, precise edge detection on product, no fringing or artifacts, Amazon Flipkart e-commerce listing ready product photo'},
          {'title': 'Portrait Studio Look', 'platform': 'Adobe Firefly', 'description': 'Portrait with studio background', 'text': 'Remove original background from this portrait and replace with professional studio gradient grey background, clean edge around hair, LinkedIn or corporate headshot ready professional look'},
          {'title': 'Wedding Background Swap', 'platform': 'Remove.bg', 'description': 'Replace wedding photo background', 'text': 'Remove background from this wedding photo and replace with beautiful palace or garden background, preserve bride and groom perfectly including saree and sherwani edges, natural composited look'},
          {'title': 'Profile Pic Transparent', 'platform': 'Adobe Firefly', 'description': 'Create transparent background PNG', 'text': 'Remove background from this portrait photo creating perfect transparent PNG, clean edges around hair and clothing, suitable for any background overlay, social media or business use'},
          {'title': 'Food Plate Isolation', 'platform': 'Remove.bg', 'description': 'Isolate food for restaurant menu', 'text': 'Remove background from this food photo and place on clean white or gradient background, perfect edge isolation around plate and garnish, restaurant menu or food app listing quality'},
          {'title': 'Fashion Model Cutout', 'platform': 'Adobe Firefly', 'description': 'Fashion model background change', 'text': 'Remove background from this fashion model photo with perfect hair edge masking, place on urban street or luxury interior background, fashion magazine composite quality'},
          {'title': 'Car Background Replace', 'platform': 'Remove.bg', 'description': 'Car on dramatic background', 'text': 'Remove parking lot background from this car photo and replace with dramatic mountain road or showroom background, perfect car edge masking, automobile advertisement composite quality'},
          {'title': 'Jewelry Transparent', 'platform': 'Adobe Firefly', 'description': 'Jewellery on transparent background', 'text': 'Remove background from this jewellery photo with precise masking around fine chain and intricate goldwork details, transparent PNG for website catalog, no reflection artifacts'},
          {'title': 'Pet Photo Studio', 'platform': 'Remove.bg', 'description': 'Pet on clean studio background', 'text': 'Remove messy home background from this pet photo and replace with clean studio backdrop, preserve all fur edges including fine wisps of hair, professional pet photography look'},
          {'title': 'ID Photo Background', 'platform': 'Adobe Firefly', 'description': 'Change ID photo background to white', 'text': 'Remove background from this portrait and apply official white or light blue ID photo background, correct sizing for passport or visa application, clean professional government ID photo'},
        ];

      case 'Face Enhance':
        return [
          {'title': 'Skin Smooth Natural', 'platform': 'Facetune', 'description': 'Natural skin smoothing', 'text': 'Enhance skin in this portrait photo with natural-looking smoothing, reduce blemishes and dark spots, even skin tone without removing texture, preserve pores for realism, natural beauty enhancement not plastic look'},
          {'title': 'Eyes Brighten Sharpen', 'platform': 'Remini', 'description': 'Enhance and brighten eyes', 'text': 'Enhance the eyes in this portrait, brighten whites of eyes, sharpen iris detail, add natural catchlight sparkle, reduce dark circles subtly, make eyes the focal point, natural enhancement'},
          {'title': 'Teeth Whiten Natural', 'platform': 'Facetune', 'description': 'Natural teeth whitening', 'text': 'Whiten teeth in this smiling portrait photo naturally, remove stains and yellowing, brighten to natural white not unrealistic bright white, preserve tooth shape and texture, believable smile enhancement'},
          {'title': 'Face Symmetry Subtle', 'platform': 'Adobe Lightroom AI', 'description': 'Subtle facial symmetry improvement', 'text': 'Subtly improve facial symmetry in this portrait using AI, gentle and natural adjustments only, preserve unique features and character, enhance without making face look artificial or altered'},
          {'title': 'Age Reduce Portrait', 'platform': 'Facetune', 'description': 'Subtle age reduction in portrait', 'text': 'Gently reduce visible aging in this portrait, soften deep lines while keeping natural character, lift slight sagging subtly, even age spots, preserve personality and authenticity of subject'},
          {'title': 'Blur Background Face Focus', 'platform': 'Remini', 'description': 'Portrait background blur enhancement', 'text': 'Enhance this portrait by adding professional bokeh background blur, keep face in sharp focus, natural depth of field simulation, DSLR portrait lens quality effect on smartphone photo'},
          {'title': 'Dark Circle Remove', 'platform': 'Adobe Lightroom AI', 'description': 'Remove dark circles under eyes', 'text': 'Remove dark circles and under-eye bags from this portrait naturally, brighten under-eye area to match skin tone, natural result not overly edited, refreshed and rested appearance'},
          {'title': 'Blurry Face Restore', 'platform': 'Remini', 'description': 'Restore blurry face in photo', 'text': 'Restore and sharpen this blurry or out-of-focus face in the photo, AI face restoration to recover facial features, sharpen eyes nose and mouth detail, usable portrait from blurry original'},
          {'title': 'Group Face Enhance', 'platform': 'Facetune', 'description': 'Enhance all faces in group photo', 'text': 'Enhance and sharpen all faces in this group photo simultaneously, brighten eyes across all subjects, subtle skin improvement on everyone, ensure all faces equally clear and flattering'},
          {'title': 'Low Light Face Fix', 'platform': 'Adobe Lightroom AI', 'description': 'Fix dark poorly lit face', 'text': 'Fix this poorly lit dark portrait, brighten face naturally, recover detail from shadows, reduce noise from high ISO, color correct skin tone, make usable portrait from bad lighting photo'},
        ];

      case 'Color Correction':
        return [
          {'title': 'Golden Hour Grade', 'platform': 'Adobe Lightroom', 'description': 'Warm golden hour color grade', 'text': 'Apply cinematic golden hour color grade to this photo, warm the highlights to golden orange, deep shadows to brown, enhance sky colors, skin tones warm and glowing, Bollywood golden light aesthetic'},
          {'title': 'Wedding Cinematic Grade', 'platform': 'VSCO', 'description': 'Wedding photo warm film grade', 'text': 'Apply beautiful wedding cinematic color grade, warm creamy highlights, soft pastel tones, lifted blacks for airy feel, subtle green tones in shadows, film photography wedding aesthetic'},
          {'title': 'Moody Dark Edit', 'platform': 'Adobe Lightroom', 'description': 'Dark dramatic color edit', 'text': 'Apply moody dark and dramatic color grade to this photo, deep crushed blacks, desaturated midtones, pull blue tones in shadows, cinematic teal and orange Hollywood film look'},
          {'title': 'Skin Tone Fix', 'platform': 'Capture One', 'description': 'Correct skin tone color cast', 'text': 'Fix and correct skin tone color cast in this portrait, remove green or yellow color cast from fluorescent lighting, set white balance correctly, natural Indian skin tone rendering'},
          {'title': 'Food Vibrance Boost', 'platform': 'Adobe Lightroom', 'description': 'Make food photo colors pop', 'text': 'Enhance colors in this food photo, boost vibrance and saturation selectively, make reds and oranges pop in curry, greens fresh and vivid, warm golden tones, appetite-stimulating food color grade'},
          {'title': 'Faded Film Aesthetic', 'platform': 'VSCO', 'description': 'Vintage faded film look', 'text': 'Apply authentic vintage faded film aesthetic to this photo, lifted blacks and faded shadows, slight color cross processing, film grain overlay, nostalgic analog photography look'},
          {'title': 'Blue Hour Night Fix', 'platform': 'Capture One', 'description': 'Fix nighttime photo blue color', 'text': 'Color correct this nighttime city photo, balance mixed artificial lighting colors, reduce excessive blue cast, warm street light to natural orange-gold, clean night photography color grade'},
          {'title': 'Product True Color', 'platform': 'Adobe Lightroom', 'description': 'True to life product color', 'text': 'Color correct this product photo to true accurate colors matching real product, remove color cast from studio lights, neutral background correction, e-commerce accurate product color representation'},
          {'title': 'Holi Colors Enhance', 'platform': 'VSCO', 'description': 'Festival Holi colors vibrant', 'text': 'Enhance colors in this Holi festival photo, boost vibrance of all color powders, make each color distinct and vivid, bright and joyful processing, festival energy in color grade'},
          {'title': 'Black White Dramatic', 'platform': 'Capture One', 'description': 'Dramatic black and white conversion', 'text': 'Convert this photo to dramatic black and white, high contrast luminosity, deep blacks and bright whites, zone system tonal range, Ansel Adams style fine art monochrome conversion'},
        ];

      case 'Style Transfer':
        return [
          {'title': 'Photo to Van Gogh', 'platform': 'Prisma', 'description': 'Photo in Van Gogh painting style', 'text': 'Transform this photo into Van Gogh Starry Night style, swirling impasto brushstrokes, bold blue and yellow palette, thick textured paint simulation, impressionist style transfer on photograph'},
          {'title': 'Portrait to Anime', 'platform': 'Stable Diffusion', 'description': 'Real portrait to anime character', 'text': 'Transform this portrait photo into anime character style, large expressive anime eyes, clean anime line art, preserved facial likeness in anime form, Studio Ghibli quality anime style transfer'},
          {'title': 'Photo to Oil Painting', 'platform': 'Prisma', 'description': 'Photo transformed to oil painting', 'text': 'Transform this photo into classical oil painting style, thick impasto brushwork, rich saturated colors, visible canvas texture, old master painting quality, museum worthy oil painting style transfer'},
          {'title': 'Portrait to Sketch', 'platform': 'Adobe Firefly', 'description': 'Photo converted to pencil sketch', 'text': 'Transform this portrait photo into detailed pencil sketch drawing, realistic pencil lines and shading, cross-hatching texture, fine art drawing quality, charcoal or graphite sketch style'},
          {'title': 'Photo to Pixel Art', 'platform': 'Stable Diffusion', 'description': 'Photo converted to pixel art', 'text': 'Transform this photo into detailed pixel art style, 16-bit retro game aesthetic, limited color palette, dithering technique, nostalgic video game pixel art style transfer'},
          {'title': 'Scene to Watercolor', 'platform': 'Prisma', 'description': 'Photo to watercolor painting', 'text': 'Transform this photo into beautiful watercolor painting, soft color washes and bleeds, white paper showing through, loose artistic style, water bleeding effects, contemporary watercolor style transfer'},
          {'title': 'Photo to Warli Art', 'platform': 'Adobe Firefly', 'description': 'Photo to Indian tribal Warli style', 'text': 'Transform this photo into Indian Warli tribal art style, white geometric stick figures on red ochre background, tribal pattern overlay, folk art style transfer preserving subject composition'},
          {'title': 'Portrait to 3D Render', 'platform': 'Stable Diffusion', 'description': 'Portrait to Pixar 3D style', 'text': 'Transform this portrait photo into Pixar 3D animation character style, stylized features, smooth 3D render quality, big expressive eyes, Pixar movie character style transfer'},
          {'title': 'Street to Cyberpunk', 'platform': 'Prisma', 'description': 'Street photo to cyberpunk style', 'text': 'Transform this street photo into cyberpunk aesthetic, neon color overlay, rain and neon reflections added, dark dystopian mood, Blade Runner 2049 style cyberpunk style transfer'},
          {'title': 'Photo to Madhubani', 'platform': 'Adobe Firefly', 'description': 'Photo to Madhubani folk art', 'text': 'Transform this photo into Madhubani folk painting style, intricate traditional line patterns, bold primary colors with black outlines, Bihar folk art aesthetic, cultural Indian art style transfer'},
        ];

      default:
        return [];
    }
  }
}
